
name: Query Tickets

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # UTC+8 7-22
    - cron: "45 0-14,23 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Action Number
        run: |
          echo $GITHUB_RUN_NUMBER

      # Runs a set of commands using the runners shell
      - name: Run Request
        env:
          FIREBASE_SERVER_KEY: ${{ secrets.FIREBASE_SERVER_KEY }}
          TRAIN_QUERY: ${{ secrets.TRAIN_QUERY }}
          TRAIN_COOKIE: ${{ secrets.TRAIN_COOKIE }}
          TRAIN_REFERER: ${{ secrets.TRAIN_REFERER }}
          CTRIP_QUERY: ${{ secrets.CTRIP_QUERY }}
          CTRIP_COOKIE: ${{ secrets.CTRIP_COOKIE }}
        run: |
          for i in {0..50}; do
            if [ -n "$TRAIN_QUERY" ]; then
              python3 train.py &
            fi
            if [ -n "$CTRIP_QUERY" ]; then
              python3 ctrip.py &
            fi
            sleep 60
          done
